# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\ProyectoPuntoDeVenta\UI\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(398, 466)
        MainWindow.setStyleSheet("background-color: rgb(21, 130, 213);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 160, 61, 31))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 230, 81, 21))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.txtUsuario = QtWidgets.QLineEdit(self.centralwidget)
        self.txtUsuario.setGeometry(QtCore.QRect(90, 190, 221, 20))
        self.txtUsuario.setStyleSheet("color: rgb(255, 255, 255);")
        self.txtUsuario.setObjectName("txtUsuario")
        self.txtpassword = QtWidgets.QLineEdit(self.centralwidget)
        self.txtpassword.setGeometry(QtCore.QRect(90, 260, 221, 20))
        self.txtpassword.setStyleSheet("color: rgb(255, 255, 255);")
        self.txtpassword.setObjectName("txtpassword")
        self.btnIniciar = QtWidgets.QPushButton(self.centralwidget)
        self.btnIniciar.setGeometry(QtCore.QRect(90, 330, 221, 51))
        self.btnIniciar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.btnIniciar.setObjectName("btnIniciar")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 30, 121, 121))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("d:\\ProyectoPuntoDeVenta\\UI\\../IMG/iniciar-sesion.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 398, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "USUARIO:"))
        self.label_2.setText(_translate("MainWindow", "CONTRASEÑA:"))
        self.btnIniciar.setText(_translate("MainWindow", "INICIAR SESIÓN"))
