# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\ProyectoPuntoDeVenta\UI\VentanaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(761, 518)
        MainWindow.setStyleSheet("background-color: rgb(21, 130, 213);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnVender = QtWidgets.QPushButton(self.centralwidget)
        self.btnVender.setGeometry(QtCore.QRect(0, 120, 211, 41))
        self.btnVender.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\ProyectoPuntoDeVenta\\UI\\../IMG/vender.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnVender.setIcon(icon)
        self.btnVender.setObjectName("btnVender")
        self.btnProductos = QtWidgets.QPushButton(self.centralwidget)
        self.btnProductos.setGeometry(QtCore.QRect(0, 160, 211, 41))
        self.btnProductos.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("d:\\ProyectoPuntoDeVenta\\UI\\../IMG/producto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnProductos.setIcon(icon1)
        self.btnProductos.setObjectName("btnProductos")
        self.btnClientes = QtWidgets.QPushButton(self.centralwidget)
        self.btnClientes.setGeometry(QtCore.QRect(0, 200, 211, 41))
        self.btnClientes.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("d:\\ProyectoPuntoDeVenta\\UI\\../IMG/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClientes.setIcon(icon2)
        self.btnClientes.setObjectName("btnClientes")
        self.btnAlmacenes = QtWidgets.QPushButton(self.centralwidget)
        self.btnAlmacenes.setGeometry(QtCore.QRect(0, 240, 211, 41))
        self.btnAlmacenes.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("d:\\ProyectoPuntoDeVenta\\UI\\../IMG/almacen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlmacenes.setIcon(icon3)
        self.btnAlmacenes.setObjectName("btnAlmacenes")
        self.btnProveedores = QtWidgets.QPushButton(self.centralwidget)
        self.btnProveedores.setGeometry(QtCore.QRect(0, 280, 211, 41))
        self.btnProveedores.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("d:\\ProyectoPuntoDeVenta\\UI\\../IMG/proveedor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnProveedores.setIcon(icon4)
        self.btnProveedores.setObjectName("btnProveedores")
        self.btnSalidas = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalidas.setGeometry(QtCore.QRect(0, 320, 211, 41))
        self.btnSalidas.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("d:\\ProyectoPuntoDeVenta\\UI\\../IMG/ingreso y salida.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalidas.setIcon(icon5)
        self.btnSalidas.setObjectName("btnSalidas")
        self.btnVentas = QtWidgets.QPushButton(self.centralwidget)
        self.btnVentas.setGeometry(QtCore.QRect(0, 360, 211, 41))
        self.btnVentas.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.btnVentas.setIcon(icon5)
        self.btnVentas.setObjectName("btnVentas")
        self.btnDetalleVentas = QtWidgets.QPushButton(self.centralwidget)
        self.btnDetalleVentas.setGeometry(QtCore.QRect(0, 400, 211, 41))
        self.btnDetalleVentas.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("d:\\ProyectoPuntoDeVenta\\UI\\../IMG/punto-de-venta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDetalleVentas.setIcon(icon6)
        self.btnDetalleVentas.setObjectName("btnDetalleVentas")
        self.btnSalir = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalir.setGeometry(QtCore.QRect(670, 20, 75, 23))
        self.btnSalir.setStyleSheet("alternate-background-color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("d:\\ProyectoPuntoDeVenta\\UI\\../IMG/letra-x (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalir.setIcon(icon7)
        self.btnSalir.setCheckable(False)
        self.btnSalir.setAutoRepeat(False)
        self.btnSalir.setObjectName("btnSalir")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 211, 121))
        self.label.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("d:\\ProyectoPuntoDeVenta\\UI\\../IMG/edusis.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 0, 551, 61))
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 440, 211, 31))
        self.label_3.setStyleSheet("background-color: rgb(23, 143, 234);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.btnVender.raise_()
        self.btnProductos.raise_()
        self.label_2.raise_()
        self.btnClientes.raise_()
        self.btnAlmacenes.raise_()
        self.btnProveedores.raise_()
        self.btnSalidas.raise_()
        self.btnVentas.raise_()
        self.btnDetalleVentas.raise_()
        self.label.raise_()
        self.btnSalir.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 761, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnVender.setText(_translate("MainWindow", " VENDER"))
        self.btnProductos.setText(_translate("MainWindow", " PRODUCTOS"))
        self.btnClientes.setText(_translate("MainWindow", " CLIENTES"))
        self.btnAlmacenes.setText(_translate("MainWindow", " ALMACENES"))
        self.btnProveedores.setText(_translate("MainWindow", " PROVEEDORES"))
        self.btnSalidas.setText(_translate("MainWindow", " SALIDAS"))
        self.btnVentas.setText(_translate("MainWindow", " VENTAS"))
        self.btnDetalleVentas.setText(_translate("MainWindow", " DETALLE VENTAS"))
        self.btnSalir.setText(_translate("MainWindow", "  SALIR"))
