Descrip=input("Descripcion del articulo: \n -->")
Precio=float(input("Precio de compra: \n -->"))
porcentaje=float(input("Porcentaje de ganancia: \n -->"))
Stock=int(input("Numero de unidades en stock: \n -->"))
##Realizar calculos
Pventa=float(Precio+Precio*(porcentaje/100))
ganancia=float(Precio*(porcentaje/100))
neto = float(ganancia*Stock)
Valoriza=float(Pventa*Stock)
Pcompra=float(Precio*Stock)
##print("Hola, %s, tu edad es %s años "%(nombre,edad))
print("Venta de %s"%(Descrip))
print ("El precio de compra C/U es: {:.2f}".format(Precio))
print ("El porcentaje ganado C/U es: {:.2f}".format(ganancia))
print ("El precio de venta C/U es: {:.2f}".format(Pventa))
print ("El precio de compra es: {:.2f}".format(Pcompra))
print ("El porcentaje ganado: {:.2f}".format(neto))
print ("La valorizacion Totales: {:.2f}".format(Valoriza))
